<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cookie_control"
 *
 * Auto generated by Extension Builder 2015-12-31
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Cookie Control',
	'description' => 'Cookie Control (Sponsored by BIBUS AG)',
	'category' => 'plugin',
	'author' => 'Azeef A S,Sivaprasad S,Siju E Raju',
	'author_email' => 'azeef@pitsolutions.com,sivaprasad.s@pitsolutions.com,siju.er@pitsolutions.com',
	'author_company' => 'PIT Solutions Pvt ltd',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '2.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0 - 7.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);